apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-secret
  namespace: default
type: Opaque
data:
  ssh-publickey: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FEYVM5cGZlbmcxcFVZVGZuQWdTY0pURCtLOVhsNTJCbWFqMFJnMVkvcVVCU3h0MURrUDYwYmhHbU1xdUlLU3B6TEx5SjVZNUJSSGFFaTJpaHhubXFaV0VZNE1TMVlOS3Jsb1d1WXhsVGpMbUUzZWpYYjM3SW9sa2ZBYWx3S1lNVlRrTVVsM0ZUWk5mK1REWDd2dWJuMFMrMEN5dmdkUFk4b3orR1B6L0g4SHIrcTRjaklRR0VFQkpvZ0VpVlFnZHRxTm5VTHJSQnZEdDFqdlFaWWUzYWl0Z1gwRk1nMTVrVklPWVo2N2xOZVR0MHRoT3BjaEIzSkI1b1d3U0x1MFcvTUJLTEQzdk5QRGRHanp2SzBTVUxxL0dVQzRTTzV6bUV6TEVjcXBoUnF5WElTNVhuTnVhK1NOSy9vaFAwbEFnZzRaVFhDVkFuWXlJTVRQblhHN0kvbWRnNUdlb3krSXVmalIxNDJidFUzRDdGZlpzS05QNnNFcGJDVHRuYXAzZGhmY1VMdzhDNFZNUUhUbnE4NXJONlNkTFRWQnVYRXVxVlovL1YySC9KVS90Q3lHbmFTZnJadDFOd1IzQ2lLMTNsekRIdjhJN21Sa1JwZ29TWjdiS0pEVTlEN2pRcGhNd2oyWFFsM3d6VTRDU082WTFlTEFyZHk3LzFWQzdCblBxZU09IGplYXJAdWJ1bnR1MjAK

